### ISSUE TITLE
logfiles gone after moving / from SD card to sata device 

### ISSUE THREAD

**Issue by hanscees** [bobafetthotmail/folder2ram#15]
Hi,
I am not sure if this place holds the code for folder2ram in omv. If it does:

I have installed omv4 on an SD card on top of raspbian on a bananapi.
After installing omv all worked well.

To spare the SD card I moved the system to a sata drive by rsyncing the / filessystem but while omv was running while rsyncing.

After I rebooted Linux / runs fine from the sata drive (/dev/sda1).
But services like nginx and proftpd do not start and report missing logfiles.
Those logfiles are present in /var/log.hdd but not in /var/log

Is there someplace where omv or folder2ram references to /dev devices directly?
Or can I tell folder2ram to re-consume /var/log.hdd?

**Comment by hanscees** [comment]
no matter why this happened, was fixed by doing
/sbin/folder2ram -umountall
and then copying missing files from log.hdd folder to /var/log and reboot.

**Comment by bobafetthotmail** [comment]
if you rsynced while the system was running you probably didn't copy the folders that folder2ram had placed in RAM (tmpfs).

foldername.hdd is the name of the original folder on disk while folder2ram is running (so both places are accessible at the same time), it seems your rsync copied that.

Before running a rsync you should stop folder2ram with **/sbin/folder2ram -umountall** (or use the interface in the OMV plugin) so that the logs and stuff is moved to disk.
Then you can start it again.

**Comment by hanscees** [comment]
thank you!
