### ISSUE TITLE
TODO status?

### ISSUE THREAD

**Issue by Spoiledbroth** [bobafetthotmail/folder2ram#8]
Hi!

I came across this by way of OMV but have since started using it on a cheaper netbook with embedded storage. I was curious if you had made any progress on the TODO listed in your readme? If so would you be open to posting some gists or a branch, or even just emailing me code so I could extend it further for my purposes? I realize you might be busy! 

Hope all is well.

Sb

**Comment by bobafetthotmail** [comment]
I didn't write anything significant for the TODO goals, sorry.

But when I wrote the goals I did preliminary google searching and I found a project I could borrow from for the last feature in the list (making a squashfs and place it in RAM), which I think is the most interesting thing for your netbook.

https://github.com/terminator14/RAM_booster

I can accept PRs to this script, but since I'm not going to develop it further you can also fork it and make it your own.

**Comment by Spoiledbroth** [comment]
Cool thanks alot! Sorry for not closing this sooner, just started a new job.
